### ISSUE TITLE
Determine which qPCRs worked

### ISSUE THREAD

**Issue by sr320** [afcoyle/fish541_lab#2]
Quick take on results
https://d.pr/v/JW1VPz

Which columns were which genes?

**Comment by ChrisMantegna** [comment]
![image](https://user-images.githubusercontent.com/81385272/170574924-22844bee-1e49-45a3-9152-d77bc2092a2d.png)

**Comment by aspencoyle** [comment]
Summary from the video:

| Column | Primer       | Summary            |
|--------|--------------|--------------------|
| 1      | SQSTM1       | worked             |
| 2      | GADD45gamma  | worked             |
| 3      | ferritin     | failed             |
| 4      | smallHSP24.1 | amplified in water |
| 5      | HSP90        | failed             |
| 6      | MT20         | not specific       |
| 7      | HSC70        | worked             |
| 8      | MT10         | amplified in water |

**Comment by sarahtanja** [comment]
Decided to use GADD45gamma as normalizing gene and HSC70 as measure of heat-shock expression in qPCRs of samples
