### ISSUE TITLE
exp_design & cDNA methods

### ISSUE THREAD

**Issue by sarahtanja** [afcoyle/fish541_lab#4]
Sarah will get a start on these methods sections before leaving for HI on 06/07/22

**Comment by zbengt** [comment]
@afcoyle Aidan could you finish up the cDNA synthesis methods. Sarah started them in a Rmd file in the methods folder.

**Comment by sarahtanja** [comment]
@afcoyle and @zbengt I just pushed a commit adding more content to the cDNA methods. They're still not totally 'flush', but I'd say they're reproducible...
