### ISSUE TITLE
Need more MMLV & oligo dT primer

### ISSUE THREAD

**Issue by sarahtanja** [afcoyle/fish541_lab#6]
I have time to come into the lab tomorrow morning @0900 (06/01/22) to make cDNA from our remaining RNA samples before @zbengt and @ocattau run the qPCRs. Limiting reagents are the MMLV reverse transcriptase and the oligo dT primer. Are these things we have 'on hand' or do we need to order them and wait for them to arrive?

**Comment by sr320** [comment]
added to -20 in lab! 🔥

**Comment by sarahtanja** [comment]
New reagents added to lab freezer, complete
