### ISSUE TITLE
'Asterisk' * triggers error Windows invalid filename 

### ISSUE THREAD

**Issue by sarahtanja** [afcoyle/fish541_lab#8]
@ocattau can you remove the '*' from your filenames? I can't pull... I think it's a windows thing

![Screenshot 2022-06-02 090027](https://user-images.githubusercontent.com/86446350/171673767-55c76971-f898-4f96-8bad-46dee18e6e97.png)

**Comment by sr320** [comment]
spaces are not great either

**Comment by sarahtanja** [comment]
under_score or dash-file tend to work best for Windows! Also, short and sweet... I've run into issues in the past with too many long file names nested into long folder names giving me errors.

**Comment by ocattau** [comment]
Done
